# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 03:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=50, verbose_name='品种名称')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, max_length=10000, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '品种',
                'ordering': ['create_time'],
                'verbose_name_plural': '品种分类',
            },
        ),
    ]
