# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogtype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogtype',
            name='remarks',
            field=models.TextField(blank=True, max_length=200, verbose_name='备注'),
        ),
    ]
