# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 03:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import doginfo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogbrand', '0001_initial'),
        ('dogtype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='狗场名称')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('phone', models.CharField(max_length=50, verbose_name='手机')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('case', models.ImageField(blank=True, upload_to='imgs', verbose_name='成功案例')),
                ('dynamic', models.CharField(blank=True, max_length=200, verbose_name='最新动态')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='狗场地址')),
                ('profile', models.CharField(blank=True, max_length=1000, verbose_name='简介')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, max_length=10000, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公司简介',
                'ordering': ['create_time'],
                'verbose_name_plural': '公司简介',
            },
        ),
        migrations.CreateModel(
            name='DogFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('ages', models.CharField(max_length=50, verbose_name='狗龄')),
                ('picture', models.CharField(max_length=50, verbose_name='图片')),
                ('desc', models.CharField(max_length=50, verbose_name='说明')),
                ('telephone', models.CharField(max_length=50, verbose_name='电话')),
                ('showtime', models.IntegerField(verbose_name='显示时间')),
                ('create_time', models.CharField(max_length=50, verbose_name='产品名称')),
                ('typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogtype.Dogtype', verbose_name='品种')),
            ],
        ),
        migrations.CreateModel(
            name='Dogfood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50, verbose_name='产品名称')),
                ('prod_picture', models.ImageField(blank=True, upload_to='imgs', verbose_name='品牌图片')),
                ('dog_age', models.CharField(blank=True, max_length=20, verbose_name='适用犬龄')),
                ('sale_url', models.CharField(blank=True, max_length=50, verbose_name='交易网址')),
                ('food_models', models.CharField(blank=True, max_length=50, verbose_name='规格')),
                ('period', models.CharField(blank=True, max_length=50, verbose_name='保质期')),
                ('netweight', models.CharField(blank=True, max_length=50, verbose_name='净含量')),
                ('dog_desc', ckeditor.fields.RichTextField(max_length=2000, verbose_name='简介')),
                ('prod_desc', ckeditor.fields.RichTextField(max_length=2000, verbose_name='产品介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dog_brandid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogbrand.Dogbrand', verbose_name='品牌')),
                ('dog_typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogtype.Dogtype', verbose_name='品种')),
            ],
            options={
                'verbose_name': '宠粮录入',
                'ordering': ['create_time'],
                'verbose_name_plural': '宠粮录入表',
            },
        ),
        migrations.CreateModel(
            name='Doginfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_code', models.CharField(default=doginfo.models.defulfs, max_length=20, verbose_name='宠物编号')),
                ('dog_name', models.CharField(max_length=50, verbose_name='宠物名称')),
                ('dog_birthday', models.DateField(verbose_name='出生日期')),
                ('dog_bodytype', models.CharField(choices=[('0', '大'), ('1', '中'), ('2', '小')], default='0', max_length=10, verbose_name='宠物体型')),
                ('dog_picture', models.ImageField(blank=True, upload_to='imgs', verbose_name='宠物图片')),
                ('dog_color', models.CharField(blank=True, max_length=10, verbose_name='宠物颜色')),
                ('owner_name', models.CharField(blank=True, max_length=20, verbose_name='主人姓名')),
                ('owner_address', models.CharField(blank=True, max_length=200, verbose_name='主人地址')),
                ('owner_telephone', models.CharField(max_length=50, verbose_name='主人电话')),
                ('owner_weixin', models.CharField(blank=True, max_length=50, verbose_name='主人微信')),
                ('sterilization', models.CharField(choices=[('0', '否'), ('1', '是')], default='0', max_length=10, verbose_name='是否绝育')),
                ('dog_sex', models.CharField(choices=[('0', '公'), ('1', '母')], default='0', max_length=10, verbose_name='性别')),
                ('Insect', models.DateField(blank=True, null=True, verbose_name='驱虫日期')),
                ('vaccine', models.DateField(blank=True, null=True, verbose_name='注射疫苗日期')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, max_length=10000, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dog_typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogtype.Dogtype', verbose_name='品种')),
            ],
            options={
                'verbose_name': '宠物简介',
                'ordering': ['create_time'],
                'verbose_name_plural': '宠物简介',
            },
        ),
        migrations.CreateModel(
            name='Dogloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=500, verbose_name='宠物名称')),
                ('lostdate', models.DateTimeField(blank=True, null=True, verbose_name='丢失时间')),
                ('lostplace', models.CharField(blank=True, max_length=100, verbose_name='丢失地点')),
                ('dog_age', models.CharField(blank=True, max_length=20, verbose_name='犬龄')),
                ('dog_sex', models.CharField(choices=[('0', '公'), ('1', '母')], default='0', max_length=10, verbose_name='性别')),
                ('owner_name', models.CharField(blank=True, max_length=20, verbose_name='主人姓名')),
                ('owner_address', models.CharField(blank=True, max_length=200, verbose_name='主人地址')),
                ('owner_telephone', models.CharField(max_length=50, verbose_name='主人电话')),
                ('dog_picture', models.ImageField(blank=True, upload_to='imgs', verbose_name='宠物图片')),
                ('dog_color', models.CharField(blank=True, max_length=10, verbose_name='宠物颜色')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, max_length=2000, verbose_name='简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dog_typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogtype.Dogtype', verbose_name='品种')),
            ],
            options={
                'verbose_name': '寻宠登记',
                'ordering': ['create_time'],
                'verbose_name_plural': '寻宠登记表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='账号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户管理',
                'ordering': ['create_time'],
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
