# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogfeed',
            options={'ordering': ['create_time'], 'verbose_name': '配种', 'verbose_name_plural': '配种'},
        ),
    ]
