# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0002_auto_20180226_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doginfo',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000, verbose_name='备注'),
        ),
    ]
