# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0004_auto_20180302_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doginfo',
            name='dog_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
    ]
