# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0006_auto_20180302_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doginfo',
            options={'verbose_name': '宠物简介', 'verbose_name_plural': '宠物简介'},
        ),
    ]
