# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0007_auto_20180302_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogloss',
            options={'verbose_name': '寻宠登记', 'verbose_name_plural': '寻宠登记表'},
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='dog_bodytype',
            field=models.IntegerField(choices=[(0, '大'), (1, '中'), (2, '小')], default=0, verbose_name='宠物体型'),
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='dog_sex',
            field=models.IntegerField(choices=[(0, '公'), (1, '母')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='sterilization',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否绝育'),
        ),
        migrations.AlterField(
            model_name='dogloss',
            name='dog_sex',
            field=models.IntegerField(choices=[(0, '公'), (1, '母')], default=0, verbose_name='性别'),
        ),
    ]
