# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-16 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0009_auto_20180416_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogbreed',
            name='sex',
            field=models.CharField(choices=[('公', '公'), ('母', '母')], max_length=10, verbose_name='性别'),
        ),
    ]
