# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-16 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0010_auto_20180416_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogbreed',
            name='ages',
            field=models.CharField(blank=True, max_length=50, verbose_name='狗龄'),
        ),
        migrations.AlterField(
            model_name='dogbreed',
            name='desc',
            field=models.CharField(blank=True, max_length=50, verbose_name='特点'),
        ),
        migrations.AlterField(
            model_name='dogbreed',
            name='showtime',
            field=models.DateTimeField(blank=True, verbose_name='显示时间'),
        ),
    ]
