# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0011_auto_20180416_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogbreed',
            name='picture',
            field=models.ImageField(blank=True, upload_to='breed', verbose_name='图片'),
        ),
    ]
