# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-16 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0012_auto_20180416_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogloss',
            old_name='owner_name',
            new_name='ownername',
        ),
        migrations.RenameField(
            model_name='dogloss',
            old_name='owner_telephone',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='dogloss',
            old_name='dog_typeid',
            new_name='typeid',
        ),
        migrations.RemoveField(
            model_name='dogloss',
            name='dog_age',
        ),
        migrations.RemoveField(
            model_name='dogloss',
            name='dog_color',
        ),
        migrations.RemoveField(
            model_name='dogloss',
            name='dog_picture',
        ),
        migrations.RemoveField(
            model_name='dogloss',
            name='dog_sex',
        ),
        migrations.RemoveField(
            model_name='dogloss',
            name='owner_address',
        ),
        migrations.RemoveField(
            model_name='dogloss',
            name='remarks',
        ),
        migrations.AddField(
            model_name='dogloss',
            name='age',
            field=models.IntegerField(blank=True, default=0, verbose_name='犬龄'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogloss',
            name='color',
            field=models.CharField(blank=True, max_length=10, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='dogloss',
            name='desc',
            field=models.CharField(blank=True, max_length=100, verbose_name='特征'),
        ),
        migrations.AddField(
            model_name='dogloss',
            name='picture',
            field=models.ImageField(blank=True, upload_to='loss', verbose_name='宠物图片'),
        ),
        migrations.AddField(
            model_name='dogloss',
            name='sex',
            field=models.CharField(blank=True, choices=[(0, '公'), (1, '母')], max_length=10, verbose_name='性别'),
        ),
    ]
