# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-16 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0013_auto_20180416_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogloss',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='犬龄'),
        ),
        migrations.AlterField(
            model_name='dogloss',
            name='sex',
            field=models.CharField(blank=True, choices=[(0, '公'), (1, '母')], max_length=10, null=True, verbose_name='性别'),
        ),
    ]
