# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-16 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0015_auto_20180416_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogloss',
            name='colors',
            field=models.CharField(max_length=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='dogloss',
            name='lostdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='丢失时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dogloss',
            name='lostplace',
            field=models.CharField(max_length=100, verbose_name='丢失地点'),
        ),
        migrations.AlterField(
            model_name='dogloss',
            name='ownername',
            field=models.CharField(max_length=20, verbose_name='主人姓名'),
        ),
    ]
