# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-16 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogtype', '0002_auto_20180302_0918'),
        ('doginfo', '0017_auto_20180416_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=1, verbose_name='颜色')),
                ('desc', models.CharField(blank=True, max_length=100, verbose_name='特征')),
                ('picture', models.ImageField(blank=True, upload_to='loss', verbose_name='宠物图片')),
                ('findplace', models.CharField(max_length=100, verbose_name='发现地点')),
                ('finddate', models.DateTimeField(verbose_name='发现时间')),
                ('findname', models.CharField(max_length=20, verbose_name='联系人姓名')),
                ('telephone', models.CharField(max_length=50, verbose_name='联系电话')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogtype.Dogtype', verbose_name='品种')),
            ],
            options={
                'verbose_name': '寻宠主',
                'verbose_name_plural': '寻宠主',
            },
        ),
    ]
