# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0018_dogowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogloss',
            name='openid',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='唯一标识'),
        ),
        migrations.AddField(
            model_name='dogowner',
            name='openid',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='唯一标识'),
        ),
    ]
