# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-25 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0019_auto_20180424_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogloss',
            name='colors',
            field=models.CharField(max_length=24, verbose_name='颜色'),
        ),
    ]
