# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-26 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0020_auto_20180425_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogloss',
            options={'ordering': ['-create_time'], 'verbose_name': '寻宠登记', 'verbose_name_plural': '寻宠登记表'},
        ),
        migrations.AlterField(
            model_name='dogloss',
            name='colors',
            field=models.CharField(max_length=24, verbose_name='宠物颜色'),
        ),
        migrations.AlterField(
            model_name='dogloss',
            name='desc',
            field=models.CharField(blank=True, max_length=100, verbose_name='宠物特征'),
        ),
        migrations.AlterField(
            model_name='dogloss',
            name='dog_name',
            field=models.CharField(max_length=500, verbose_name='宠物昵称'),
        ),
        migrations.AlterField(
            model_name='dogloss',
            name='lostdate',
            field=models.DateField(verbose_name='丢失时间'),
        ),
        migrations.AlterField(
            model_name='dogloss',
            name='typeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogtype.Dogtype', verbose_name='宠物品种'),
        ),
    ]
