# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-27 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0021_auto_20180426_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogloss',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='loss', verbose_name='宠物图片'),
        ),
        migrations.AlterField(
            model_name='dogloss',
            name='telephone',
            field=models.CharField(max_length=50, verbose_name='主人手机'),
        ),
        migrations.AlterField(
            model_name='dogowner',
            name='colors',
            field=models.CharField(max_length=1, verbose_name='宠物颜色'),
        ),
        migrations.AlterField(
            model_name='dogowner',
            name='desc',
            field=models.CharField(blank=True, max_length=100, verbose_name='宠物特征'),
        ),
        migrations.AlterField(
            model_name='dogowner',
            name='finddate',
            field=models.DateField(verbose_name='发现时间'),
        ),
        migrations.AlterField(
            model_name='dogowner',
            name='typeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogtype.Dogtype', verbose_name='宠物品种'),
        ),
    ]
