# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-27 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0022_auto_20180427_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogowner',
            options={'verbose_name': '寻宠物主人', 'verbose_name_plural': '寻宠物主人'},
        ),
        migrations.AlterField(
            model_name='dogowner',
            name='colors',
            field=models.CharField(max_length=24, verbose_name='宠物颜色'),
        ),
    ]
