# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0023_auto_20180427_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogloss',
            options={'ordering': ['-create_time'], 'verbose_name': '寻宠登记', 'verbose_name_plural': '寻宠登记'},
        ),
        migrations.AlterModelOptions(
            name='dogowner',
            options={'ordering': ['-create_time'], 'verbose_name': '寻宠物主人', 'verbose_name_plural': '寻宠物主人'},
        ),
    ]
