# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogtype', '0003_auto_20180425_0926'),
        ('doginfo', '0024_auto_20180502_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogAdoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='领养人')),
                ('telephone', models.CharField(max_length=20, verbose_name='电话')),
                ('record', models.CharField(max_length=100, verbose_name='饲养宠物记录')),
                ('requirement', models.CharField(max_length=200, verbose_name='对宠物要求')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('openid', models.CharField(blank=True, max_length=120, null=True, verbose_name='唯一标识')),
            ],
            options={
                'verbose_name': '宠物领养',
                'verbose_name_plural': '宠物领养',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DogDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='昵称')),
                ('colors', models.CharField(blank=True, max_length=10, null=True, verbose_name='颜色')),
                ('ages', models.CharField(blank=True, max_length=50, null=True, verbose_name='狗龄')),
                ('sex', models.CharField(blank=True, choices=[('公', '公'), ('母', '母')], max_length=10, null=True, verbose_name='性别')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='特征')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='delivery/%Y%m%d/', verbose_name='照片')),
                ('ownername', models.CharField(max_length=20, verbose_name='狗主姓名')),
                ('telephone', models.CharField(max_length=50, verbose_name='联系方式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('openid', models.CharField(blank=True, max_length=120, null=True, verbose_name='唯一标识')),
                ('typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogtype.Dogtype', verbose_name='品种')),
            ],
            options={
                'verbose_name': '宠物送养',
                'verbose_name_plural': '宠物送养',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='dogbreed',
            options={'ordering': ['-create_time'], 'verbose_name': '宠物配种', 'verbose_name_plural': '宠物配种'},
        ),
        migrations.AlterModelOptions(
            name='dogfood',
            options={'ordering': ['-create_time'], 'verbose_name': '宠粮录入', 'verbose_name_plural': '宠粮录入表'},
        ),
        migrations.AlterField(
            model_name='dogloss',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='loss/%Y%m%d/', verbose_name='宠物图片'),
        ),
        migrations.AlterField(
            model_name='dogowner',
            name='picture',
            field=models.ImageField(blank=True, upload_to='loss/%Y%m%d/', verbose_name='宠物图片'),
        ),
    ]
