# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0025_auto_20180503_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadoption',
            name='record',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='饲养宠物记录'),
        ),
    ]
