# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0026_auto_20180503_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogloss',
            options={'ordering': ['-id'], 'verbose_name': '寻宠登记', 'verbose_name_plural': '寻宠登记表'},
        ),
        migrations.AlterField(
            model_name='dogbreed',
            name='showtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='显示时间'),
        ),
        migrations.AlterField(
            model_name='dogloss',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='loss/%Y%m%d/', verbose_name='宠物图片'),
        ),
    ]
