# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 15:03
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0027_auto_20180503_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogloss',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=200, null=True, upload_to='loss/%Y%m%d/', verbose_name='宠物图片'),
        ),
    ]
