# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginfo', '0030_auto_20180503_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogloss',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='loss/%Y%m%d/', verbose_name='宠物图片'),
        ),
    ]
